# frontend/app.py

try:
    __import__('pysqlite3')
    import sys
    sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
except ImportError:
    pass


import sys
import os

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

import streamlit as st
from crew.main import kickoff_query                     # expects: kickoff_query(query: str, domain_directive: str)
from crew.tasks import DOMAIN_DIRECTIVES                # dict of domain -> directive text


# Page config
st.set_page_config(
    page_title="The Maple Protocol – Canada AI Strategy Assistant",
    layout="wide",
)


# --- Chat input + disclaimer layout tweaks ---
st.markdown(
    """
    <style>
    /* Lift the chat input a bit to make room for the disclaimer */
    [data-testid="stChatInput"] {
        margin-bottom: 3.0rem !important;
    }

    /* Small disclaimer aligned with main content width */
    .chat-disclaimer {
        position: fixed;
        bottom: 5.0rem;
        left: 58%;
        transform: translateX(-50%);
        font-size: 0.75rem;
        color: #888888;
        text-align: center;
        z-index: 999;
        max-width: 60rem;        /* roughly matches main content width */
        width: 100%;
        padding: 0 1rem;         /* keeps text off the edges */
    }
    </style>
    <div class="chat-disclaimer">
        Responses are generated by an AI model and may be inaccurate or incomplete.
        Always cross-check important information with the original report and other sources.
    </div>
    """,
    unsafe_allow_html=True,
)

# Header with logo
logo_path = os.path.join(CURRENT_DIR, "assets", "maple_protocol_logo.png")

# Make the logo column narrow and reduce the gap between columns
header_col1, header_col2 = st.columns([1, 6], gap="medium")

with header_col1:
    st.write("") 
    st.write("")
    if os.path.exists(logo_path):
        st.image(logo_path, width=140)
    else:
        st.write("The Maple Protocol")

with header_col2:
    st.markdown(
        """
        <h1 style="line-height: 1.15;">
            The Maple Protocol<br>
            Canada AI Strategy Assistant
        </h1>
        """,
        unsafe_allow_html=True,
    )
    st.markdown(
        """
        **MIE 1624 Course Project – Team Maple Protocol**  
        *Interactive AI assistant grounded in our original analysis and supporting evidence from the Maple Protocol report.*
        """,
        unsafe_allow_html=True,
    )

# Sidebar
with st.sidebar:
    st.subheader("How to use this assistant")
    st.markdown(
        "- Ask about Canada’s AI strategy, competitiveness, policy, talent, compute, or adoption.\n"
        "- Responses are grounded in our Maple Protocol report and supporting reference material.\n"
    )

    st.divider()

    st.subheader("Answer Focus")
    st.caption("Tailor the answer style and focus to this aspect of AI competitiveness.")

    answer_focus_help = """
    **Answer focus options**
    - **general** – balanced overview based on the full report.  
    - **policy** – highlights government levers, regulation, funding programs, and institutional design.  
    - **research** – emphasizes R&D capacity, talent, labs, publications, and academic–industry linkages.  
    - **product** – focuses on commercialization, startups, scale-ups, and market adoption of AI products.  
    - **manufacturing** – emphasizes compute infrastructure, hardware, fabs, and industrial AI capacity.
    """

    selected_domain = st.selectbox(
        "Options",
        ["general", "policy", "research", "product", "manufacturing"],
        index=0,
        help=answer_focus_help,
        # label_visibility="visible"  # default; we can just omit this line
    )

    if st.button("Clear chat", use_container_width=True):
        st.session_state.history = []


# Chat state
if "history" not in st.session_state:
    # list[dict]: {"role": "user"|"assistant", "content": str}
    st.session_state.history = []


#  Chat input
prompt = st.chat_input("Ask about Canada’s AI strategy and competitiveness...")
if prompt:
    # Show user message immediately
    st.session_state.history.append({"role": "user", "content": prompt})

    directive = DOMAIN_DIRECTIVES[selected_domain]
    with st.spinner("Thinking..."):
        try:
            answer = kickoff_query(query=prompt, domain_directive=directive)
        except Exception as e:
            answer = f"Sorry, something went wrong: `{e}`"

    st.session_state.history.append({"role": "assistant", "content": str(answer)})



# Render conversation
chatbot_icon_path = os.path.join(CURRENT_DIR, "assets", "chatbot_icon.png")

user_icon_path = os.path.join(CURRENT_DIR, "assets", "user_icon.png")

for msg in st.session_state.history:
    # Determine which icon to show
    if msg["role"] == "assistant":
        avatar_icon = chatbot_icon_path 
    else:
        avatar_icon = user_icon_path

    with st.chat_message(msg["role"], avatar=avatar_icon):
        st.markdown(msg["content"])


# Quick starter questions
st.divider()
st.caption("Quick Maple Protocol questions:")
cols = st.columns(3)

examples = [
    "What is Canada’s Position Relative to Global AI Leaders?",
    "What determines national AI competitiveness?",
    "Outline the implementation roadmap phases from 0 to 60+ months.",
]

for i, ex in enumerate(examples):
    if cols[i % 3].button(ex, use_container_width=True):
        st.session_state.history.append({"role": "user", "content": ex})

        directive = DOMAIN_DIRECTIVES[selected_domain]
        with st.spinner("Thinking..."):
            try:
                answer = kickoff_query(query=ex, domain_directive=directive)
            except Exception as e:
                answer = f"Sorry, something went wrong: `{e}`"

        st.session_state.history.append({"role": "assistant", "content": str(answer)})
        st.rerun()
